[tool.poetry]
name = "compiler"
version = "0.1.0"
description = ""
authors = ["Jonathan Leeming <jonathan@leeming.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.11"
rply = "^0.7.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
